-- PostgreSQL schema converted from MySQL dump
-- Source: skyit_traxx_schema.sql

--
-- ------------------------------------------------------


--
-- Table structure for table "api_accidentfilemodel"
--

DROP TABLE IF EXISTS "api_accidentfilemodel" CASCADE;
CREATE TABLE "api_accidentfilemodel" (
  "file_id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "file_type" varchar(150) NOT NULL,
  "file_name" text NOT NULL,
  "file_url" text NOT NULL,
  "bytes" bigint NOT NULL,
  "file_created" timestamp(6) NOT NULL,
  "accident_id" int DEFAULT NULL,
  PRIMARY KEY ("file_id")
);

CREATE INDEX "api_accidentfilemode_accident_id_a356de30_fk_api_accid" ON "api_accidentfilemodel" ("accident_id");


--
--


--
-- Table structure for table "api_accidentmodel"
--

DROP TABLE IF EXISTS "api_accidentmodel" CASCADE;
CREATE TABLE "api_accidentmodel" (
  "accident_id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "custom_id" varchar(100) NOT NULL,
  "estimated_return_date" timestamp(6) DEFAULT NULL,
  "accident_report_completed" boolean NOT NULL,
  "is_equipment_failure" boolean NOT NULL,
  "notification_ack" boolean NOT NULL,
  "evaluation_required" boolean NOT NULL,
  "is_resolved" boolean NOT NULL,
  "is_preventable" boolean NOT NULL,
  "is_operational" boolean NOT NULL,
  "date_returned_to_service" timestamp(6) DEFAULT NULL,
  "accident_summary" text,
  "downtime_hours" double precision NOT NULL,
  "date_created" timestamp(6) NOT NULL,
  "date_modified" timestamp(6) NOT NULL,
  "VIN_id" varchar(100) NOT NULL,
  "created_by_id" int DEFAULT NULL,
  "disposal_id" int DEFAULT NULL,
  "location_id" int DEFAULT NULL,
  "modified_by_id" int DEFAULT NULL,
  PRIMARY KEY ("accident_id")
);

CREATE INDEX "api_accidentmodel_VIN_id_3130961a_fk_api_assetmodel_VIN" ON "api_accidentmodel" ("VIN_id");
CREATE INDEX "api_accidentmodel_created_by_id_3c566486_fk_api_detai" ON "api_accidentmodel" ("created_by_id");
CREATE INDEX "api_accidentmodel_disposal_id_a16512ac_fk_api_asset" ON "api_accidentmodel" ("disposal_id");
CREATE INDEX "api_accidentmodel_location_id_1b207e0d_fk_api_locat" ON "api_accidentmodel" ("location_id");
CREATE INDEX "api_accidentmodel_modified_by_id_ef02950f_fk_api_detai" ON "api_accidentmodel" ("modified_by_id");


--
--


--
-- Table structure for table "api_accidentmodelhistory"
--

DROP TABLE IF EXISTS "api_accidentmodelhistory" CASCADE;
CREATE TABLE "api_accidentmodelhistory" (
  "accident_history_id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "custom_id" varchar(100) NOT NULL,
  "estimated_return_date" timestamp(6) DEFAULT NULL,
  "accident_report_completed" boolean NOT NULL,
  "is_equipment_failure" boolean NOT NULL,
  "notification_ack" boolean NOT NULL,
  "evaluation_required" boolean NOT NULL,
  "is_resolved" boolean NOT NULL,
  "is_preventable" boolean NOT NULL,
  "is_operational" boolean NOT NULL,
  "date_returned_to_service" timestamp(6) DEFAULT NULL,
  "accident_summary" text,
  "downtime_hours" double precision NOT NULL,
  "date" timestamp(6) NOT NULL,
  "accident_id" int NOT NULL,
  "location_id" int DEFAULT NULL,
  "modified_by_id" int DEFAULT NULL,
  PRIMARY KEY ("accident_history_id")
);

CREATE INDEX "api_accidentmodelhis_accident_id_7eec054b_fk_api_accid" ON "api_accidentmodelhistory" ("accident_id");
CREATE INDEX "api_accidentmodelhis_location_id_9d5dc35c_fk_api_locat" ON "api_accidentmodelhistory" ("location_id");
CREATE INDEX "api_accidentmodelhis_modified_by_id_d676ee67_fk_api_detai" ON "api_accidentmodelhistory" ("modified_by_id");


--
--


--
-- Table structure for table "api_acquisitioncost"
--

DROP TABLE IF EXISTS "api_acquisitioncost" CASCADE;
CREATE TABLE "api_acquisitioncost" (
  "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "total_cost" double precision NOT NULL,
  "taxes" double precision NOT NULL,
  "administrative_cost" double precision NOT NULL,
  "misc_cost" double precision NOT NULL,
  "date_created" timestamp(6) NOT NULL,
  "date_updated" timestamp(6) NOT NULL,
  "VIN_id" varchar(100) DEFAULT NULL,
  "created_by_id" int DEFAULT NULL,
  "currency_id" int DEFAULT NULL,
  "location_id" int DEFAULT NULL,
  "modified_by_id" int DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "api_acquisitioncost_VIN_id_3526fd6e_fk_api_assetmodel_VIN" ON "api_acquisitioncost" ("VIN_id");
CREATE INDEX "api_acquisitioncost_created_by_id_2a71eeed_fk_api_detai" ON "api_acquisitioncost" ("created_by_id");
CREATE INDEX "api_acquisitioncost_currency_id_e73277cd_fk_api_currency_id" ON "api_acquisitioncost" ("currency_id");
CREATE INDEX "api_acquisitioncost_location_id_5bd5e472_fk_api_locat" ON "api_acquisitioncost" ("location_id");
CREATE INDEX "api_acquisitioncost_modified_by_id_1662932d_fk_api_detai" ON "api_acquisitioncost" ("modified_by_id");


--
--


-- Foreign key constraints
ALTER TABLE "api_accidentfilemodel" ADD CONSTRAINT "api_accidentfilemode_accident_id_a356de30_fk_api_accid" FOREIGN KEY ("accident_id") REFERENCES "api_accidentmodel" ("accident_id");
ALTER TABLE "api_accidentmodel" ADD CONSTRAINT "api_accidentmodel_created_by_id_3c566486_fk_api_detai" FOREIGN KEY ("created_by_id") REFERENCES "api_detaileduser" ("detailed_user_id");
ALTER TABLE "api_accidentmodel" ADD CONSTRAINT "api_accidentmodel_disposal_id_a16512ac_fk_api_asset" FOREIGN KEY ("disposal_id") REFERENCES "api_assetdisposalmodel" ("id");
ALTER TABLE "api_accidentmodel" ADD CONSTRAINT "api_accidentmodel_location_id_1b207e0d_fk_api_locat" FOREIGN KEY ("location_id") REFERENCES "api_locationmodel" ("location_id");
ALTER TABLE "api_accidentmodel" ADD CONSTRAINT "api_accidentmodel_modified_by_id_ef02950f_fk_api_detai" FOREIGN KEY ("modified_by_id") REFERENCES "api_detaileduser" ("detailed_user_id");
ALTER TABLE "api_accidentmodel" ADD CONSTRAINT "api_accidentmodel_VIN_id_3130961a_fk_api_assetmodel_VIN" FOREIGN KEY ("VIN_id") REFERENCES "api_assetmodel" ("VIN");
ALTER TABLE "api_accidentmodelhistory" ADD CONSTRAINT "api_accidentmodelhis_accident_id_7eec054b_fk_api_accid" FOREIGN KEY ("accident_id") REFERENCES "api_accidentmodel" ("accident_id");
ALTER TABLE "api_accidentmodelhistory" ADD CONSTRAINT "api_accidentmodelhis_location_id_9d5dc35c_fk_api_locat" FOREIGN KEY ("location_id") REFERENCES "api_locationmodel" ("location_id");
ALTER TABLE "api_accidentmodelhistory" ADD CONSTRAINT "api_accidentmodelhis_modified_by_id_d676ee67_fk_api_detai" FOREIGN KEY ("modified_by_id") REFERENCES "api_detaileduser" ("detailed_user_id");
ALTER TABLE "api_acquisitioncost" ADD CONSTRAINT "api_acquisitioncost_created_by_id_2a71eeed_fk_api_detai" FOREIGN KEY ("created_by_id") REFERENCES "api_detaileduser" ("detailed_user_id");
ALTER TABLE "api_acquisitioncost" ADD CONSTRAINT "api_acquisitioncost_currency_id_e73277cd_fk_api_currency_id" FOREIGN KEY ("currency_id") REFERENCES "api_currency" ("id");
ALTER TABLE "api_acquisitioncost" ADD CONSTRAINT "api_acquisitioncost_location_id_5bd5e472_fk_api_locat" FOREIGN KEY ("location_id") REFERENCES "api_locationmodel" ("location_id");
ALTER TABLE "api_acquisitioncost" ADD CONSTRAINT "api_acquisitioncost_modified_by_id_1662932d_fk_api_detai" FOREIGN KEY ("modified_by_id") REFERENCES "api_detaileduser" ("detailed_user_id");
ALTER TABLE "api_acquisitioncost" ADD CONSTRAINT "api_acquisitioncost_VIN_id_3526fd6e_fk_api_assetmodel_VIN" FOREIGN KEY ("VIN_id") REFERENCES "api_assetmodel" ("VIN");
